# Generated by Django 2.0.2 on 2018-03-03 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0003_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topic.Meeting')),
            ],
        ),
        migrations.RemoveField(
            model_name='topic',
            name='status',
        ),
        migrations.DeleteModel(
            name='TopicStatus',
        ),
    ]
