# Generated by Django 2.0.2 on 2018-03-03 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0004_auto_20180303_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='action',
            name='due_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
